env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  freebsd_instance:
    matrix:
      image_family: freebsd-14-0-snap
      image_family: freebsd-13-1
      image_family: freebsd-12-3
  install_script:
    - sed -i.bak -e 's,quarterly,latest,' /etc/pkg/FreeBSD.conf
    - env ASSUME_ALWAYS_YES=yes pkg bootstrap -f
    - pkg upgrade -y
    - pkg install -y evdev-proto meson ninja pkgconf
  script: 
    - env CPPFLAGS='-isystem /usr/local/include' CFLAGS='-isystem /usr/local/include' meson _build
    - ninja -v -C _build
